version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: rollup
    versions:
    - 1.32.1
    - 2.45.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
    - 8.3.2
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: lint-staged
    versions:
    - 10.5.3
    - 10.5.4
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
  - dependency-name: acorn
    versions:
    - 7.4.1
  - dependency-name: mri
    versions:
    - 1.1.6
  - dependency-name: https-proxy-agent
    versions:
    - 5.0.0
  - dependency-name: rimraf
    versions:
    - 3.0.2
