name: Verification

on: [pull_request]

jobs:
    verification:
        name: Verification (${{ matrix.os }})

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v5

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.14

            - run: bun --version

            - name: Use Node.js 20.x
              uses: actions/setup-node@v5
              with:
                  node-version: 20.x

            - run: bun install --frozen-lockfile
            - run: bun run build
            - run: bun run test
